# Generated by Django 3.2.9 on 2021-11-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211120_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.SmallIntegerField(null=True),
        ),
    ]
